### PR TITLE
Fix flatten

### PR DESCRIPTION
**Pull request by yakky**
See #33 for discussion

### CODE REVIEW

**Comment by yakky** [comment]
@ojii added values checks too

**Comment by ojii** [comment]
@yakky, thanks for the updated PR. Did you check this against django CMS to see if it actually fixes the issue you had there?

**Comment by yakky** [comment]
@ojii yes. Well, CMS has its own share of issues in this area, but I'm nailing them down in divio/django-cms#4998

**Comment by ojii** [comment]
Tentatively scheduling a 0.7.2 to include this by EOW.

**Comment by ojii** [comment]
Merged and released as 0.7.2, thanks @cyberstar and @yakky

**Pull request merged**
